/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/mi3laVB2TwqfVImh/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#f3cad4']} />
      <group {...props} dispose={null}>
        <scene name="Scene">
          <group name="Menuicon" position={[6.29, 670.81, -893.31]}>
            <mesh
              name="Text"
              geometry={nodes.Text.geometry}
              material={materials.White}
              castShadow
              receiveShadow
              position={[-9.29, -16.65, 24.05]}
              rotation={[0, -Math.PI / 2, 0]}
            />
            <group name="Menu" position={[-6.29, -10.57, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.3}>
              <group name="Container" position={[0, 35.23, -12.31]} scale={1}>
                <mesh
                  name="menu"
                  geometry={nodes.menu.geometry}
                  material={materials.White}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[-46.03, -2125.96, 23.61]}
                />
                <mesh
                  name="icon-bg"
                  geometry={nodes['icon-bg'].geometry}
                  material={materials.main}
                  castShadow
                  receiveShadow
                  position={[0, 0, -37.61]}
                />
              </group>
            </group>
          </group>
          <group name="Exiticon" position={[6.29, 670.81, -1274.51]}>
            <group name="exit" position={[-45.72, -4.79, -9.81]} scale={[1, 0.92, 0.71]}>
              <mesh
                name="Rectangle"
                geometry={nodes.Rectangle.geometry}
                material={materials.White}
                castShadow
                receiveShadow
                position={[2.5, -0.02, -9.61]}
                rotation={[0, -Math.PI / 2, 0]}
              />
              <mesh
                name="Rectangle 3"
                geometry={nodes['Rectangle 3'].geometry}
                material={materials.White}
                castShadow
                receiveShadow
                position={[2.5, -9.88, -34.07]}
                rotation={[-1.25, -1.45, -1.41]}
                scale={[0.45, 0.67, 1]}
              />
              <mesh
                name="Rectangle 2"
                geometry={nodes['Rectangle 2'].geometry}
                material={materials.White}
                castShadow
                receiveShadow
                position={[2.5, 2.88, -34.94]}
                rotation={[0.56, -1.19, 1.03]}
                scale={[0.52, 0.62, 1]}
              />
              <mesh
                name="Rectangle 31"
                geometry={nodes['Rectangle 31'].geometry}
                material={materials.White}
                castShadow
                receiveShadow
                position={[-2.5, -21.67, -1.01]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.66, 0.62, 1]}
              />
              <mesh
                name="Rectangle 21"
                geometry={nodes['Rectangle 21'].geometry}
                material={materials.White}
                castShadow
                receiveShadow
                position={[2.5, 21.67, 1.01]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.66, 0.62, 1]}
              />
              <mesh
                name="Rectangle1"
                geometry={nodes.Rectangle1.geometry}
                material={materials.White}
                castShadow
                receiveShadow
                position={[2.5, -0.78, 14.9]}
                rotation={[0, -Math.PI / 2, 0]}
                scale={[0.66, 0.62, 1]}
              />
            </group>
            <group name="Exit" position={[-6.29, -10.57, -19.14]} rotation={[0, -Math.PI / 2, 0]} scale={0.3}>
              <group name="Container1" position={[0, 35.23, -12.31]} scale={1}>
                <mesh
                  name="exit1"
                  geometry={nodes.exit1.geometry}
                  material={materials.White}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[-46.03, -1048.65, 23.61]}
                />
                <mesh
                  name="icon-bg1"
                  geometry={nodes['icon-bg1'].geometry}
                  material={materials.main}
                  castShadow
                  receiveShadow
                  position={[0, 0, -37.61]}
                />
              </group>
            </group>
          </group>
          <group name="Musicicon" position={[0, 660.24, -1081.12]} rotation={[0, -Math.PI / 2, 0]} scale={0.3}>
            <group name="Container2" position={[0, 35.23, -12.31]} scale={1}>
              <mesh
                name="music"
                geometry={nodes.music.geometry}
                material={materials.White}
                castShadow
                receiveShadow
                position={[-46.03, 64.22, 23.61]}
              />
              <mesh
                name="icon-bg2"
                geometry={nodes['icon-bg2'].geometry}
                material={materials.main}
                castShadow
                receiveShadow
                position={[0, 0, -37.61]}
              />
            </group>
          </group>
          <group name="Diarybutton" position={[-583.23, 78.11, 1493.81]}>
            <group name="Diarybutton1" position={[-3.28, 0, 548.37]} rotation={[0, -Math.PI / 2, 0]}>
              <group name="container" position={[0, 0, -9.96]}>
                <mesh
                  name="Diary"
                  geometry={nodes.Diary.geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[0, -2.55, 13.18]}
                />
                <mesh
                  name="Button BG"
                  geometry={nodes['Button BG'].geometry}
                  material={materials.White}
                  castShadow
                  receiveShadow
                  position={[0, 0, 0.18]}
                />
              </group>
            </group>
          </group>
          <group name="Schedulebutton" position={[-583.23, -47.34, 1489.64]}>
            <group name="Schedulebutton1" position={[1.7, 87.58, 552.54]} rotation={[0, -Math.PI / 2, 0]}>
              <group name="Base_Button Instance" position={[0, -143.17, 4.98]}>
                <group name="container1" position={[0, 0, -9.96]}>
                  <mesh
                    name="Schedule"
                    geometry={nodes.Schedule.geometry}
                    material={materials['Untitled Material']}
                    castShadow
                    receiveShadow
                    position={[0, -2.55, 13.18]}
                  />
                  <mesh
                    name="Button BG1"
                    geometry={nodes['Button BG1'].geometry}
                    material={materials.main}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0.18]}
                  />
                </group>
              </group>
            </group>
          </group>
          <group name="Menu1" position={[-547.35, 5.49, 2076.05]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh
              name="Title"
              geometry={nodes.Title.geometry}
              material={materials['Title Material']}
              castShadow
              receiveShadow
              position={[14.79, 288.17, 13.35]}
            />
            <mesh
              name="Background"
              geometry={nodes.Background.geometry}
              material={materials['Background Material']}
              castShadow
              receiveShadow
              position={[0, -92.16, -13.35]}
            />
          </group>
          <group name="Buttons" position={[792.79, -6837.09, 10060.45]} rotation={[0, -Math.PI / 2, 0]}>
            <group name="Button set1" position={[51.41, -22.15, 31.79]}>
              <group name="Button-Base" position={[-55.88, 158.89, 7.38]}>
                <group name="container2" position={[0, 0, -9.96]}>
                  <mesh
                    name="Diary1"
                    geometry={nodes.Diary1.geometry}
                    material={materials['Diary1 Material']}
                    castShadow
                    receiveShadow
                    position={[0, -2.55, 13.18]}
                  />
                  <mesh
                    name="Button BG2"
                    geometry={nodes['Button BG2'].geometry}
                    material={materials.White}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0.18]}
                  />
                </group>
              </group>
              <group name="Button-Primary" position={[-55.88, 50.9, 2.4]}>
                <group name="Base_Button Instance1" position={[0, 0, 4.98]}>
                  <group name="container3" position={[0, 0, -9.96]}>
                    <mesh
                      name="Diary2"
                      geometry={nodes.Diary2.geometry}
                      material={materials['Untitled Material']}
                      castShadow
                      receiveShadow
                      position={[0, -2.55, 13.18]}
                    />
                    <mesh
                      name="Button BG3"
                      geometry={nodes['Button BG3'].geometry}
                      material={materials.Blue}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0.18]}
                    />
                  </group>
                </group>
              </group>
              <group name="Button-Danger" position={[-55.88, -56.84, 2.4]}>
                <group name="Base_Button Instance2" position={[0, 0, 4.98]} rotation={[0, 0, 0]}>
                  <group name="container4" position={[0, 0, -9.96]}>
                    <mesh
                      name="Diary3"
                      geometry={nodes.Diary3.geometry}
                      material={materials['Untitled Material']}
                      castShadow
                      receiveShadow
                      position={[0, -2.55, 13.18]}
                    />
                    <mesh
                      name="Button BG4"
                      geometry={nodes['Button BG4'].geometry}
                      material={materials['']}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0.18]}
                    />
                  </group>
                </group>
              </group>
            </group>
            <mesh
              name="Menu2"
              geometry={nodes.Menu2.geometry}
              material={materials['Menu2 Material']}
              castShadow
              receiveShadow
              position={[-27.02, 236.15, 13.35]}
            />
            <mesh
              name="Background1"
              geometry={nodes.Background1.geometry}
              material={materials['Background1 Material']}
              castShadow
              receiveShadow
              position={[0, -444.7, -13.35]}
            />
          </group>
          <directionalLight
            name="Light "
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-3610.2915}
            shadow-camera-right={3610.2915}
            shadow-camera-top={3610.2915}
            shadow-camera-bottom={-3610.2915}
            position={[-5483.3, 1338.71, 5709.66]}
            rotation={[2.96, 0.86, 1.44]}
            scale={[-2.29, 1, 26.94]}
          />
          <OrthographicCamera
            name="Camera"
            makeDefault={true}
            zoom={0.5}
            far={100000}
            near={-100000}
            position={[-21706.21, 0, 286.45]}
            rotation={[0, -1.56, 0]}
            scale={1}
          />
          <group name="Radio" position={[492.99, -198.27, -641.05]} rotation={[0, -Math.PI / 2, 0]} scale={0.7}>
            <mesh
              name="light-2"
              geometry={nodes['light-2'].geometry}
              material={materials['light-2 Material']}
              castShadow
              receiveShadow
              position={[-19.22, -18.34, 52.95]}
              scale={[1.46, 1.24, 1.24]}
            />
            <mesh
              name="light"
              geometry={nodes.light.geometry}
              material={materials['light Material']}
              castShadow
              receiveShadow
              position={[-42.86, -18.34, 52.95]}
              scale={[1.46, 1.24, 1.24]}
            />
            <mesh
              name="Merged Geometry"
              geometry={nodes['Merged Geometry'].geometry}
              material={materials['Merged Geometry Material']}
              castShadow
              receiveShadow
              position={[-30.76, 29.09, 54.21]}
              scale={1.32}
            />
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials['Sphere Material']}
              castShadow
              receiveShadow
              position={[39.74, 29.72, 61.44]}
              scale={1.45}
            />
            <mesh
              name="button"
              geometry={nodes.button.geometry}
              material={materials['button Material']}
              castShadow
              receiveShadow
              position={[36.69, -18.13, 55.72]}
              scale={1.32}
            />
            <mesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials['Cylinder Material']}
              castShadow
              receiveShadow
              position={[39.77, 29.44, 56.24]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={1.45}
            />
            <mesh
              name="body"
              geometry={nodes.body.geometry}
              material={materials['body Material']}
              castShadow
              receiveShadow
              position={[0, 14.52, 6.57]}
              scale={1.45}
            />
          </group>
          <group
            name="Clock"
            position={[726.13, 527.79, 641.91]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1.92, 1.92, 0.96]}
          >
            <mesh
              name="Rectangle 4"
              geometry={nodes['Rectangle 4'].geometry}
              material={materials.toggle}
              castShadow
              receiveShadow
              position={[13.9, 4.08, 4.18]}
              rotation={[0, 0, -1.22]}
              scale={1}
            />
            <group name="Rectangle 32" position={[2.36, 1.65, 6.18]} rotation={[0, 0, 0.03]} scale={[0.9, 1, 1]}>
              <mesh
                name="Rectangle 33"
                geometry={nodes['Rectangle 33'].geometry}
                material={materials.toggle}
                castShadow
                receiveShadow
                position={[0.58, 15.21, -2]}
                rotation={[0, 0, -0.05]}
                scale={[1.02, 1, 1]}
              />
            </group>
            <mesh
              name="Sphere1"
              geometry={nodes.Sphere1.geometry}
              material={materials['Sphere1 Material']}
              castShadow
              receiveShadow
              position={[1.45, -0.21, 9.42]}
            />
            <mesh
              name="Ellipse 2"
              geometry={nodes['Ellipse 2'].geometry}
              material={materials['Ellipse 2 Material']}
              castShadow
              receiveShadow
              position={[1.71, -0.86, 3.24]}
            />
            <mesh
              name="Rectangle 22"
              geometry={nodes['Rectangle 22'].geometry}
              material={materials['Rectangle 22 Material']}
              castShadow
              receiveShadow
              position={[1.84, -0.3, 1.91]}
            />
            <mesh
              name="Torus"
              geometry={nodes.Torus.geometry}
              material={materials['Torus Material']}
              castShadow
              receiveShadow
              position={[1.34, 0.73, 7]}
            />
            <mesh
              name="Ellipse"
              geometry={nodes.Ellipse.geometry}
              material={materials.dark}
              castShadow
              receiveShadow
              position={[0, 0, -12.42]}
            />
          </group>
          <group name="CharacterSet" position={[240.82, -215.85, -36.79]}>
            <group name="Character" position={[-16.43, -69.15, -5.98]} rotation={[0, 1.22, 0]} scale={1.35}>
              <group
                name="Dinosaur-eye-r"
                position={[-54.84, 308.28, -41.71]}
                rotation={[-0.82, -0.94, 0.73]}
                scale={[-0.3, 0.25, 0.17]}
              >
                <mesh
                  name="Cube 28"
                  geometry={nodes['Cube 28'].geometry}
                  material={materials['Cube 28 Material']}
                  castShadow
                  receiveShadow
                  position={[-1.17, 8.52, 4.76]}
                  rotation={[0, 0, 2.36]}
                />
                <mesh
                  name="Cylinder 2"
                  geometry={nodes['Cylinder 2'].geometry}
                  material={materials['Cylinder 2 Material']}
                  castShadow
                  receiveShadow
                  position={[0, 8.89, 4.73]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={1}
                />
              </group>
              <group name="head" position={[1.53, 271.15, -44.56]} rotation={[0.12, -0.01, -0.09]} scale={1}>
                <mesh
                  name="Cube 15"
                  geometry={nodes['Cube 15'].geometry}
                  material={materials['Cube 15 Material']}
                  castShadow
                  receiveShadow
                  position={[11.41, -1.05, 29.62]}
                  rotation={[0, Math.PI / 9, 0]}
                  scale={1}
                />
                <mesh
                  name="Cube 14"
                  geometry={nodes['Cube 14'].geometry}
                  material={materials['Cube 14 Material']}
                  castShadow
                  receiveShadow
                  position={[-21.35, -1.05, 28.72]}
                  rotation={[0, -Math.PI / 9, 0]}
                  scale={1}
                />
                <mesh
                  name="Cube 13"
                  geometry={nodes['Cube 13'].geometry}
                  material={materials['Cube 13 Material']}
                  castShadow
                  receiveShadow
                  position={[-21.98, 8.29, 29.17]}
                  rotation={[-0.04, -0.41, -0.2]}
                  scale={1}
                />
                <mesh
                  name="Cube 12"
                  geometry={nodes['Cube 12'].geometry}
                  material={materials['Cube 12 Material']}
                  castShadow
                  receiveShadow
                  position={[12.6, 4.37, 31.35]}
                  rotation={[-0.1, 0.28, 0.2]}
                  scale={1}
                />
                <mesh
                  name="Ellipse 21"
                  geometry={nodes['Ellipse 21'].geometry}
                  material={materials['Ellipse 21 Material']}
                  castShadow
                  receiveShadow
                  position={[-24.64, -21.51, 23.43]}
                  rotation={[0.26, -0.58, 0]}
                  scale={1}
                />
                <mesh
                  name="Ellipse1"
                  geometry={nodes.Ellipse1.geometry}
                  material={materials['Ellipse1 Material']}
                  castShadow
                  receiveShadow
                  position={[16.55, -20.69, 24.79]}
                  rotation={[0.26, 0.56, 0]}
                  scale={1}
                />
                <mesh
                  name="Cube 9"
                  geometry={nodes['Cube 9'].geometry}
                  material={materials['Cube 9 Material']}
                  castShadow
                  receiveShadow
                  position={[1.3, -27.6, 26.37]}
                  rotation={[0.14, -0.46, -2.93]}
                  scale={[0.93, 1, 0.67]}
                />
                <mesh
                  name="Cube 2"
                  geometry={nodes['Cube 2'].geometry}
                  material={materials['Cube 2 Material']}
                  castShadow
                  receiveShadow
                  position={[38.89, -9, -6.07]}
                  scale={[-1, 1, 1]}
                />
                <mesh
                  name="Cube"
                  geometry={nodes.Cube.geometry}
                  material={materials['Cube Material']}
                  castShadow
                  receiveShadow
                  position={[-46.02, -12.67, -6.07]}
                />
                <mesh
                  name="hair"
                  geometry={nodes.hair.geometry}
                  material={materials['hair Material']}
                  castShadow
                  receiveShadow
                  position={[-6.16, 38.5, -31.08]}
                  rotation={[-Math.PI / 6, 0, 0]}
                  scale={[1.04, 1, 1]}
                />
                <mesh
                  name="Sphere 2"
                  geometry={nodes['Sphere 2'].geometry}
                  material={materials['Sphere 2 Material']}
                  castShadow
                  receiveShadow
                  position={[-2.88, -8.51, -8.67]}
                />
              </group>
              <group name="Glasses" position={[-1.71, 274.53, -50.15]} rotation={[0.22, -0.02, -0.05]} scale={1.22}>
                <mesh
                  name="Cylinder1"
                  geometry={nodes.Cylinder1.geometry}
                  material={materials['Cylinder1 Material']}
                  castShadow
                  receiveShadow
                  position={[0.06, 5.4, 33.96]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={1}
                />
                <mesh
                  name="Cube 3"
                  geometry={nodes['Cube 3'].geometry}
                  material={materials['Cube 3 Material']}
                  castShadow
                  receiveShadow
                  position={[33.6, 1.21, 30.85]}
                  rotation={[0, 1.4, 0]}
                  scale={1}
                />
                <mesh
                  name="Cube 21"
                  geometry={nodes['Cube 21'].geometry}
                  material={materials['Cube 21 Material']}
                  castShadow
                  receiveShadow
                  position={[-33, 0.81, 30.81]}
                  rotation={[-Math.PI, 1.4, -Math.PI]}
                  scale={1}
                />
                <mesh
                  name="Torus 2"
                  geometry={nodes['Torus 2'].geometry}
                  material={materials['Torus 2 Material']}
                  castShadow
                  receiveShadow
                  position={[18.4, 0.83, 33.98]}
                  rotation={[0, 0, -0.02]}
                  scale={1}
                />
                <mesh
                  name="Torus1"
                  geometry={nodes.Torus1.geometry}
                  material={materials['Torus1 Material']}
                  castShadow
                  receiveShadow
                  position={[-17.94, 1.59, 33.98]}
                  rotation={[0, 0, -0.02]}
                  scale={1}
                />
              </group>
              <group
                name="Group 5"
                position={[-29.31, -168.52, 15.44]}
                rotation={[0.87, 0, 0.26]}
                scale={[1.8, 1.76, 1.71]}
              >
                <mesh
                  name="Merged Geometry1"
                  geometry={nodes['Merged Geometry1'].geometry}
                  material={materials['Merged Geometry1 Material']}
                  castShadow
                  receiveShadow
                  position={[0.25, -6.17, 4.41]}
                  rotation={[-0.79, 0.54, -0.19]}
                  scale={[0.83, 0.89, 0.83]}
                />
                <mesh
                  name="Cube 4"
                  geometry={nodes['Cube 4'].geometry}
                  material={materials['Cube 4 Material']}
                  castShadow
                  receiveShadow
                  position={[0.03, -5.56, -27.01]}
                  rotation={[Math.PI, 0, 0]}
                  scale={0.9}
                />
                <mesh
                  name="Cube 31"
                  geometry={nodes['Cube 31'].geometry}
                  material={materials['Cube 31 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.5, -10.06, 16.62]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1}
                />
                <mesh
                  name="Cube 22"
                  geometry={nodes['Cube 22'].geometry}
                  material={materials['Cube 22 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.4, -9.73, 0.39]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1}
                />
                <mesh
                  name="Rectangle 23"
                  geometry={nodes['Rectangle 23'].geometry}
                  material={materials['Rectangle 23 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.45, -20.06, -0.01]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1}
                />
              </group>
              <group
                name="Group 4"
                position={[28.78, -238.18, 130.7]}
                rotation={[-0.09, 0, 0]}
                scale={[1.8, 1.66, 1.8]}
              >
                <mesh
                  name="Merged Geometry2"
                  geometry={nodes['Merged Geometry2'].geometry}
                  material={materials['Merged Geometry2 Material']}
                  castShadow
                  receiveShadow
                  position={[0.04, -6.17, 4.52]}
                  rotation={[0.09, 0.35, 0]}
                  scale={[0.83, 0.89, 0.83]}
                />
                <mesh
                  name="Cube 41"
                  geometry={nodes['Cube 41'].geometry}
                  material={materials['Cube 41 Material']}
                  castShadow
                  receiveShadow
                  position={[0.03, -5.56, -27.01]}
                  rotation={[Math.PI, 0, 0]}
                  scale={0.9}
                />
                <mesh
                  name="Cube 32"
                  geometry={nodes['Cube 32'].geometry}
                  material={materials['Cube 32 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.5, -10.06, 16.62]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1}
                />
                <mesh
                  name="Cube 23"
                  geometry={nodes['Cube 23'].geometry}
                  material={materials['Cube 23 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.4, -9.73, 0.39]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1}
                />
                <mesh
                  name="Rectangle 24"
                  geometry={nodes['Rectangle 24'].geometry}
                  material={materials['Rectangle 24 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.45, -20.06, -0.01]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={1}
                />
              </group>
              <mesh
                name="Cube 11"
                geometry={nodes['Cube 11'].geometry}
                material={materials['Cube 11 Material']}
                castShadow
                receiveShadow
                position={[24.35, 169.23, -43.04]}
                rotation={[-0.72, 0.22, 0.03]}
                scale={[1.48, 0.51, 0.46]}
              />
              <mesh
                name="pen"
                geometry={nodes.pen.geometry}
                material={materials['pen Material']}
                castShadow
                receiveShadow
                position={[-51.59, 235.05, -45.23]}
                rotation={[0.48, -0.23, -0.21]}
                scale={1}
              />
              <mesh
                name="pants"
                geometry={nodes.pants.geometry}
                material={materials['pants Material']}
                castShadow
                receiveShadow
                position={[-3.67, 20.63, -73.2]}
                rotation={[0, 0.05, 0]}
                scale={1}
              />
              <mesh
                name="Cube 17"
                geometry={nodes['Cube 17'].geometry}
                material={materials['Cube 17 Material']}
                castShadow
                receiveShadow
                position={[-2.19, 116.88, -71.94]}
                scale={[1, 1, 0.95]}
              />
              <mesh
                name="body1"
                geometry={nodes.body1.geometry}
                material={materials['body1 Material']}
                castShadow
                receiveShadow
                position={[-5.07, 112.17, -71.74]}
              />
            </group>
            <group name="Chair" position={[-146.87, -265.5, -21.51]} scale={[0.64, 0.99, 0.66]}>
              <mesh
                name="Cube 33"
                geometry={nodes['Cube 33'].geometry}
                material={materials['Cube 33 Material']}
                castShadow
                receiveShadow
                position={[70.48, -13.2, -67.54]}
                rotation={[0.09, 0.02, -1.48]}
                scale={[0.98, 1, 1]}
              />
              <mesh
                name="Cube 24"
                geometry={nodes['Cube 24'].geometry}
                material={materials['Cube 24 Material']}
                castShadow
                receiveShadow
                position={[-71.76, -13.2, -67.54]}
                rotation={[0.09, 0, -1.66]}
                scale={[0.98, 1, 1]}
              />
              <mesh
                name="Cube 34"
                geometry={nodes['Cube 34'].geometry}
                material={materials['Cube 34 Material']}
                castShadow
                receiveShadow
                position={[70.48, -13.2, 68.88]}
                rotation={[-0.09, -0.02, -1.48]}
                scale={[0.98, 1, 1]}
              />
              <mesh
                name="Cube1"
                geometry={nodes.Cube1.geometry}
                material={materials['Cube1 Material']}
                castShadow
                receiveShadow
                position={[-71.76, -13.2, 68.88]}
                rotation={[-0.09, 0.01, -1.66]}
                scale={[0.98, 1, 1]}
              />
              <mesh
                name="Cylinder2"
                geometry={nodes.Cylinder2.geometry}
                material={materials['Cylinder2 Material']}
                castShadow
                receiveShadow
                position={[0, 152.2, 0]}
                rotation={[0, -Math.PI / 2, 0]}
              />
            </group>
          </group>
          <group name="Lamp" position={[544.74, 271.11, -404.03]} scale={1.65}>
            <mesh
              name="Cylinder 4"
              geometry={nodes['Cylinder 4'].geometry}
              material={materials['Cylinder 4 Material']}
              castShadow
              receiveShadow
              position={[0.25, -107.09, -0.71]}
              scale={0.85}
            />
            <mesh
              name="Cylinder 6"
              geometry={nodes['Cylinder 6'].geometry}
              material={materials['Cylinder 6 Material']}
              castShadow
              receiveShadow
              position={[-0.16, -65.35, -0.71]}
              scale={0.85}
            />
            <mesh
              name="Cylinder 5"
              geometry={nodes['Cylinder 5'].geometry}
              material={materials['Cylinder 5 Material']}
              castShadow
              receiveShadow
              position={[-0.16, -149.66, -0.71]}
              scale={0.85}
            />
            <mesh
              name="Cylinder 3"
              geometry={nodes['Cylinder 3'].geometry}
              material={materials['Cylinder 3 Material']}
              castShadow
              receiveShadow
              position={[-0.53, -212.52, 1.57]}
              scale={1}
            />
            <mesh
              name="Cylinder 21"
              geometry={nodes['Cylinder 21'].geometry}
              material={materials['Cylinder 21 Material']}
              castShadow
              receiveShadow
              position={[-0.25, -296.92, 0.71]}
            />
          </group>
          <group name="Decoration" position={[759.13, 350.15, -94.2]}>
            <group name="Notes" position={[0.02, -46.77, -181.02]} rotation={[0, -Math.PI / 2, 0]} scale={0.7}>
              <mesh
                name="Cube 35"
                geometry={nodes['Cube 35'].geometry}
                material={materials['Cube 35 Material']}
                castShadow
                receiveShadow
                position={[-0.7, 0.52, 10.65]}
                scale={1.08}
              />
              <mesh
                name="Cylinder3"
                geometry={nodes.Cylinder3.geometry}
                material={materials['Cylinder3 Material']}
                castShadow
                receiveShadow
                position={[-0.11, 0.85, 33.37]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.08}
              />
              <mesh
                name="Cube 25"
                geometry={nodes['Cube 25'].geometry}
                material={materials['Cube 25 Material']}
                castShadow
                receiveShadow
                position={[-6.14, -30.65, 6.7]}
                rotation={[0, 0, -0.09]}
                scale={1.35}
              />
              <mesh
                name="Cube2"
                geometry={nodes.Cube2.geometry}
                material={materials['Cube2 Material']}
                castShadow
                receiveShadow
                position={[6.07, -31.13, 13.07]}
                rotation={[0, 0, 0.09]}
                scale={1.35}
              />
              <mesh
                name="Rectangle 25"
                geometry={nodes['Rectangle 25'].geometry}
                material={materials['Rectangle 25 Material']}
                castShadow
                receiveShadow
                position={[287.24, 80.64, -42.13]}
                rotation={[0, 0, 0]}
                scale={[0.88, 0.94, 0.92]}
              />
            </group>
            <mesh
              name="Board-text"
              geometry={nodes['Board-text'].geometry}
              material={materials.dark}
              castShadow
              receiveShadow
              position={[-9.91, 115.36, -167.08]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[3.32, 3.17, 1.43]}
            />
            <mesh
              name="Ellipse 3"
              geometry={nodes['Ellipse 3'].geometry}
              material={materials['Ellipse 3 Material']}
              castShadow
              receiveShadow
              position={[-14.53, 117.84, 140.15]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.55, 0.44, 0.52]}
            />
            <mesh
              name="Ellipse 22"
              geometry={nodes['Ellipse 22'].geometry}
              material={materials['Ellipse 22 Material']}
              castShadow
              receiveShadow
              position={[-14.53, 117.84, 108.39]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.55, 0.44, 0.52]}
            />
            <mesh
              name="Ellipse2"
              geometry={nodes.Ellipse2.geometry}
              material={materials['Ellipse2 Material']}
              castShadow
              receiveShadow
              position={[-14.53, 117.84, 75.63]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.55, 0.44, 0.52]}
            />
            <mesh
              name="Rectangle 9"
              geometry={nodes['Rectangle 9'].geometry}
              material={materials['Rectangle 9 Material']}
              castShadow
              position={[-13.68, -99.49, 247.7]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.65, 0.71, 0.78]}
            />
            <mesh
              name="Rectangle 8"
              geometry={nodes['Rectangle 8'].geometry}
              material={materials['Rectangle 8 Material']}
              castShadow
              position={[-13.68, 35.21, 247.7]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.65, 0.71, 0.78]}
            />
            <mesh
              name="Rectangle 91"
              geometry={nodes['Rectangle 91'].geometry}
              material={materials['Rectangle 91 Material']}
              castShadow
              position={[-13.68, -99.49, 108.03]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.65, 0.71, 0.78]}
            />
            <mesh
              name="Rectangle 6"
              geometry={nodes['Rectangle 6'].geometry}
              material={materials['Rectangle 6 Material']}
              castShadow
              position={[-13.68, 35.21, 108.03]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.65, 0.71, 0.78]}
            />
            <mesh
              name="Rectangle 5"
              geometry={nodes['Rectangle 5'].geometry}
              material={materials['Rectangle 5 Material']}
              castShadow
              receiveShadow
              position={[-3.47, -16.51, 175.7]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.64, 0.43, 0.61]}
            />
            <mesh
              name="Rectangle 51"
              geometry={nodes['Rectangle 51'].geometry}
              material={materials['Rectangle 51 Material']}
              castShadow
              position={[1.77, -17.63, 175.21]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.59, 0.66, 0.64]}
            />
          </group>
          <group name="Calendar" position={[734.78, 302.91, -59.86]} scale={[0.98, 0.94, 0.98]}>
            <mesh
              name="Rectangle 34"
              geometry={nodes['Rectangle 34'].geometry}
              material={materials['Rectangle 34 Material']}
              castShadow
              receiveShadow
              position={[35.59, 45.98, -14.54]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[0.63, 0.7, 0.66]}
            />
          </group>
          <mesh
            name="Book-red-small"
            geometry={nodes['Book-red-small'].geometry}
            material={materials['Book-red-small Material']}
            castShadow
            receiveShadow
            position={[695.08, -155.86, -683.71]}
            rotation={[-Math.PI / 2, -1.4, -Math.PI / 2]}
            scale={1}
          />
          <mesh
            name="Book-red-big"
            geometry={nodes['Book-red-big'].geometry}
            material={materials['Book-red-big Material']}
            castShadow
            receiveShadow
            position={[770.31, -101.7, -667.05]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          />
          <mesh
            name="Book-pink-middle"
            geometry={nodes['Book-pink-middle'].geometry}
            material={materials['Book-pink-middle Material']}
            castShadow
            receiveShadow
            position={[747.82, -136.2, -667.05]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1}
          />
          <group name="Diary4" position={[427.6, -174.52, -67.2]} scale={[0.77, 0.72, 0.76]}>
            <mesh
              name="Rectangle2"
              geometry={nodes.Rectangle2.geometry}
              material={materials['Rectangle2 Material']}
              castShadow
              receiveShadow
              position={[-4.14, 10.06, 27.72]}
              rotation={[-Math.PI / 2, -Math.PI / 9, -Math.PI / 2]}
              scale={[0.8, 1, 1]}
            />
            <mesh
              name="Rectangle3"
              geometry={nodes.Rectangle3.geometry}
              material={materials['Rectangle3 Material']}
              castShadow
              receiveShadow
              position={[3.42, -9.4, 0]}
              rotation={[-Math.PI / 2, -Math.PI / 9, -Math.PI / 2]}
              scale={1}
            />
          </group>
          <group name="Tablet" position={[427.6, -181.5, -67.2]} scale={[0.77, 0.72, 0.76]}>
            <mesh
              name="Cube 42"
              geometry={nodes['Cube 42'].geometry}
              material={materials['Cube 42 Material']}
              castShadow
              receiveShadow
              position={[120.14, -9.39, -233.33]}
              rotation={[0, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 36"
              geometry={nodes['Cube 36'].geometry}
              material={materials['Cube 36 Material']}
              castShadow
              receiveShadow
              position={[120.14, -9.39, 233.31]}
              rotation={[0, 0, 0]}
              scale={1}
            />
            <mesh
              name="Cube 43"
              geometry={nodes['Cube 43'].geometry}
              material={materials['Cube 43 Material']}
              castShadow
              receiveShadow
              position={[3.73, -4.74, -233.33]}
              rotation={[0, 0, -1.22]}
              scale={1}
            />
            <mesh
              name="Cube 26"
              geometry={nodes['Cube 26'].geometry}
              material={materials['Cube 26 Material']}
              castShadow
              receiveShadow
              position={[3.73, -4.74, 233.31]}
              rotation={[0, 0, -1.22]}
              scale={1}
            />
            <mesh
              name="Cube 44"
              geometry={nodes['Cube 44'].geometry}
              material={materials['Cube 44 Material']}
              castShadow
              receiveShadow
              position={[7.63, -63.45, -233.33]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={1}
            />
            <mesh
              name="Cube3"
              geometry={nodes.Cube3.geometry}
              material={materials['Cube3 Material']}
              castShadow
              receiveShadow
              position={[7.63, -63.45, 233.31]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={1}
            />
          </group>
          <group name="Plant" position={[460.59, -289.14, 712.71]} rotation={[0, -0.04, 0]} scale={[0.93, 0.75, 0.75]}>
            <mesh
              name="Cube 27"
              geometry={nodes['Cube 27'].geometry}
              material={materials['Cube 27 Material']}
              castShadow
              receiveShadow
              position={[15.33, 90.95, -1.22]}
              rotation={[0, Math.PI / 4, 0]}
              scale={1}
            />
            <mesh
              name="Cube 37"
              geometry={nodes['Cube 37'].geometry}
              material={materials['Cube 37 Material']}
              castShadow
              receiveShadow
              position={[-21.33, 13.1, 36.98]}
              rotation={[-3.05, -Math.PI / 4, -3.05]}
              scale={1.05}
            />
            <mesh
              name="Cube 45"
              geometry={nodes['Cube 45'].geometry}
              material={materials['Cube 45 Material']}
              castShadow
              receiveShadow
              position={[37.57, -65.59, -107]}
              rotation={[-0.04, 1.22, -0.22]}
              scale={1}
            />
            <mesh
              name="Cube 5"
              geometry={nodes['Cube 5'].geometry}
              material={materials['Cube 5 Material']}
              castShadow
              receiveShadow
              position={[-12.89, -31.14, 51.83]}
              rotation={[-3.11, 1.3, -2.91]}
              scale={1.05}
            />
            <mesh
              name="Cube4"
              geometry={nodes.Cube4.geometry}
              material={materials['Cube4 Material']}
              castShadow
              receiveShadow
              position={[17.45, -42.1, 91.53]}
              rotation={[0, -1.22, -0.17]}
              scale={1}
            />
            <mesh
              name="Ellipse 31"
              geometry={nodes['Ellipse 31'].geometry}
              material={materials['Ellipse 31 Material']}
              castShadow
              receiveShadow
              position={[6.87, -137.16, 1.3]}
              rotation={[-Math.PI / 2, 0, -1.98]}
              scale={1.54}
            />
            <mesh
              name="Plant Base"
              geometry={nodes['Plant Base'].geometry}
              material={materials['Plant Base Material']}
              castShadow
              receiveShadow
              position={[13.95, -371.94, 0.56]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={1.67}
            />
          </group>
          <group name="Table" position={[516.1, -445.52, -216.83]} scale={0.7}>
            <mesh
              name="Cylinder 31"
              geometry={nodes['Cylinder 31'].geometry}
              material={materials['Cylinder 31 Material']}
              castShadow
              receiveShadow
              position={[262.37, -38.32, -709.39]}
              scale={1}
            />
            <mesh
              name="Cylinder 22"
              geometry={nodes['Cylinder 22'].geometry}
              material={materials['Cylinder 22 Material']}
              castShadow
              receiveShadow
              position={[262.37, -38.32, 862.8]}
              scale={1}
            />
            <mesh
              name="Cylinder 32"
              geometry={nodes['Cylinder 32'].geometry}
              material={materials['Cylinder 32 Material']}
              castShadow
              receiveShadow
              position={[-249.05, -35.67, -709.39]}
              scale={1}
            />
            <mesh
              name="Cylinder4"
              geometry={nodes.Cylinder4.geometry}
              material={materials['Cylinder4 Material']}
              castShadow
              receiveShadow
              position={[-249.05, -38.32, 862.8]}
              scale={1}
            />
            <mesh
              name="Rectangle4"
              geometry={nodes.Rectangle4.geometry}
              material={materials['Rectangle4 Material']}
              castShadow
              receiveShadow
              position={[0, 230.16, 91.5]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={1}
            />
          </group>
          <group name="carpet" position={[52.43, -650.95, -164.26]}>
            <mesh
              name="Ellipse 23"
              geometry={nodes['Ellipse 23'].geometry}
              material={materials['Ellipse 23 Material']}
              castShadow
              receiveShadow
              position={[0, 7.39, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.09, 1.09, 1.66]}
            />
            <mesh
              name="Ellipse3"
              geometry={nodes.Ellipse3.geometry}
              material={materials['Ellipse3 Material']}
              castShadow
              receiveShadow
              position={[0, -12.39, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[1.09, 1.09, 1.66]}
            />
          </group>
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
